# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-2yE-4rF9d9p4y-15DHvPlDjPTSH3GZ3
"""

# prompt: #PROGRAMA QUE IDENTIFICA EL CUADRANTE EN EL QUE SE ENCUENTRA EL PUNTO

while True:
  x = int(input("Ingrese la coordenada x (diferente de 0): "))
  y = int(input("Ingrese la coordenada y (diferente de 0): "))

  if x == 0 or y == 0:
    print("Las coordenadas no pueden ser 0. Intente de nuevo.")
    continue

  if x > 0 and y > 0:
    cuadrante = "I"
  elif x < 0 and y > 0:
    cuadrante = "II"
  elif x < 0 and y < 0:
    cuadrante = "III"
  else:
    cuadrante = "IV"

  print("El punto ({}, {}) se encuentra en el cuadrante {}.".format(x, y, cuadrante))