# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zhDDMTShwwwNjZOfEzPMLAEJY3ZUXDEg
"""

#PROGRAMA PARA VALIDAR PALABRAS DE ACUERDO A SU LONGITUD SI LA PALABRA INGRESADA ES MENOR DE 4 Y MAYOR DE 8 CARACTERES LA PALABRA ES INCORRECTA ESTANDO EN ESE RANGO SERA CORRECTA
num_palabras = int(input("Ingrese el número de palabras: "))
correctas = 0
incorrectas = 0

for i in range(num_palabras):
  palabra = input("Ingrese una palabra: ")
  if len(palabra) < 4:
    print("Hacen falta letras.")
    incorrectas += 1
  elif len(palabra) > 8:
    print("Sobran letras.")
    incorrectas += 1
  else:
    print("La palabra es correcta.")
    correctas += 1

print("\nPalabras correctas:", correctas)
print("Palabras incorrectas:", incorrectas)

input("Presione ENTER para salir...")

